### ISSUE TITLE
[FEATURE REQUEST]: Add show private key feature

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#627] opened 2021-01-12 10:20 UTC
https://github.com/KomodoPlatform/developer-docs/pull/158

that's a useful feature and many users want/need that afaik

**Comment by lightspeed393** [comment] 2021-01-12 15:38
Duplicate of #588

**Comment by smk762** [comment] 2021-01-21 05:51
Implemented in https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/599

**Closed by smk762** 2021-01-21 05:51 UTC
Labels: 0.4.0, P1, enhancement
