### ISSUE TITLE
[BUG]: ADEX  5.6 beta NOT LOADING ON MACBOOK AIR 

### ISSUE THREAD

**Issue by ilienongithub** [KomodoPlatform/atomicDEX-Desktop#1902] opened 2022-08-01 19:14 UTC
**Describe the bug**
I downloaded 5.6 beta but it wont open it get stuck at Initializing MM2

I am using a MacbookAir with M1 chip and Monterey 12.0.1

any ideas

<img width="294" alt="Screenshot 2022-08-01 at 20 13 46" src="https://user-images.githubusercontent.com/90349751/182228010-31920a7f-2a3e-4aff-9d31-974b535855b9.png">

**Comment by tonymorony** [comment] 2022-08-03 13:44
Hi! Thank you for the issue opening. Is this issue actual still on your side?
Collecting of more information is needed to help you resolve this problem.
I think it might be resolved more promptly if you write in #support channel on our Discord server https://komodoplatform.com/discord

**Comment by ilnatomicdex** [comment] 2022-08-12 22:53
I have tried everthing to get it to work, removing virus prtection etc but no luck.  cipi  said "i suspect the problem is a workaround they added for another problem in a 3rd-party package, this one https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/ci_tools_atomic_dex/ci_scripts/osx_script.sh#L9-L10
this 3rd-party package does not compile or link or whatever with the original version
and i guess my change to macos-12 has overwritten this workaround of them
but needs to be investigated. Thats about it. Kind regards Liam

**Comment by ilienongithub** [comment] 2022-08-24 18:24
Still have the same problim any ideas ?

**Comment by cipig** [comment] 2022-08-26 21:26
setting this to `macos-12`: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/.github/workflows/atomicdex-desktop-ci.yml#L43 likely solves the problem, but raises new ones

**Comment by ilienongithub** [comment] 2022-08-29 13:40
Morning all, any sign of a soloution to this problim ?

**Comment by ilienongithub** [comment] 2023-01-29 16:05
still have the same problim

**Comment by smk762** [comment] 2023-01-30 07:02
Have you tried 0.5.7?

**Comment by ilienongithub** [comment] 2023-01-30 09:55
Yes Just tried 5.7 beta again, 1st it opens with no coins showing. Then I do a wallet reset and it wont open any more.
Any Ideas ?

**Comment by ilienongithub** [comment] 2023-01-30 10:12
cipi version works fine.   https://github.com/cipig/atomicDEX-Desktop/actions/runs/4038784264

**Comment by smk762** [comment] 2023-01-31 08:11
> Yes Just tried 5.7 beta again, 1st it opens with no coins showing. Then I do a wallet reset and it wont open any more. Any Ideas ?

This could be due to "zombie" instance of mm2 which didnt exit properly when resetting - if cipi's build works now the 0.5.7 should also. I'll close this issue for now, please reopen or ping me on Discord if you have any more issues later.

**Closed by smk762** 2023-01-31 08:11 UTC
Labels: bug
