### ISSUE TITLE
[FEATURE REQUEST]: Best orders selection popup move into simple trading widget

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/atomicDEX-Desktop#986] opened 2021-06-15 10:05 UTC
let's discuss it during the call

![image](https://user-images.githubusercontent.com/24797699/122034511-cd502880-cdfb-11eb-8cf1-7c1dc7ee599e.png)

cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/889

**Comment by Milerius** [comment] 2021-06-15 10:35
Duplicate of #981

**Closed** 2021-06-15 10:36 UTC
Labels: 0.5.0, enhancement
