### ISSUE TITLE
[BUG]: 5.6 BETA; Price no showing in wallet

### ISSUE THREAD

**Issue by ilienongithub** [KomodoPlatform/atomicDEX-Desktop#1901] opened 2022-08-01 19:06 UTC
**Describe the bug**
the price of ILN is not showing in your wallet. there were trades done in both the last 10 min and 24 hours. Price should come fron Nomics.

If you go to do a swap on   ILN the price is there on the nomics chart.

**To Reproduce**
1. Add asset ILN
2. Click on any of our ILN coins/tokens 
3. No price

**Expected behavior**
Price should show
![ILON 22](https://user-images.githubusercontent.com/90349751/182226388-4ec2cc92-d995-45de-b0c5-55e13548ebc9.JPG)
![ILN Price](https://user-images.githubusercontent.com/90349751/182226395-b79e5d79-622e-4729-9452-4a279aaac12f.JPG)

Tried on windows 10

**Comment by cipig** [comment] 2022-08-01 19:10
prices older then 600s (10 minutes) are removed here: https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/api/komodo_prices/komodo.prices.cpp#L83 (expire_at=600)... only if coin is listed on coinpaprika, prices older then 10 minutes are shown from there as a last resort... but ILN is not on coinpaprika
would be nice to increase expire_at, most small cap coins don't have any trades in last 10 minutes anyway

**Comment by ilienongithub** [comment] 2022-08-01 20:02
Ok so the problim I am seeing is it taks a min 15min for the price on Nomics to update and as your using Nomics charts it would make sence to allow the time for the price on the chart to be relfected, as it is  based on your seetings of 10mins no trades will ever show from Nomics. Can you help ?

**Comment by ilienongithub** [comment] 2022-08-01 20:38
If the ADEX team could reach out to Nomics to see if they could update the price to every say 5 min this would solve this issue. This is me just thinking out loud. Or if you can increase the 10 min window to longer to allow for trades to show.

**Comment by tonymorony** [comment] 2022-08-03 13:45
Thank you for the issue opening!

I'm closing this one as a duplicate of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1904 

We'll look into this problem during the current sprint

**Closed by tonymorony** 2022-08-03 13:45 UTC
Labels: bug
