### ISSUE TITLE
[BUG]: DEXtop - Support button / Go to Support Guides - Link Invalid

### ISSUE THREAD

**Issue by auroracoin101** [KomodoPlatform/atomicDEX-Desktop#1359] opened 2021-10-06 11:20 UTC
**Describe the bug**
Broken / Invalid komodoplatform.com link

**To Reproduce**
1. Click on Support link on Desktop  (below Settings)
2. Click on 3rd link  (after discord,twitter)  'Go To Support Guides'
3.  Web page opens to   support.komodoplatform.com/support/home
4.  Receive Freshdesk "404 type" error 
                Freshdesk Support Desk
                We couldn't find support.komodoplatform.com
                May be this is still fresh!
                You can claim it now at http://www.freshdesk.com/signupwith following

**Expected behavior**
Go to AtomicDEX - Support Guides   ( i was looking for API info ) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Brave Browser
 - Version 0.5.2

**Additional context**
![There is no helpdesk here! - Brave-11-17-55](https://user-images.githubusercontent.com/86576259/136193060-c2108e14-9d9f-41db-9c6a-75dbf1b1040c.png)

**Comment by tonymorony** [comment] 2021-12-03 16:25
thank you for the issue opening!
the problem is fixed now (https://support.komodoplatform.com/support/home redirecting to https://forum.komodoplatform.com/tags/c/support/guides/16/collections)

**Closed by tonymorony** 2021-12-03 16:25 UTC
Labels: bug
