### ISSUE TITLE
[BUG]: Unexpected cursor growth on piechart hover

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/atomicDEX-Desktop#1772] opened 2022-05-17 14:24 UTC
On OSX, sometimes moving the cursor over the poi chart on portfolio page results in a temporary cursor size increase.

https://user-images.githubusercontent.com/35845239/168833308-13635d9c-a794-4033-a03e-1440f0e3a92e.mp4

Credit to @Canialon for finding it - I've also confirmed on my end. 
Unable to replicate so far in Linux or Windows.

Nothing in logs, suspect a possible QT bug.

**Comment by Canialon** [comment] 2022-05-25 15:38
I believe that this is not a bug of our application but iOS in general. This bug is repeated everywhere on iOS.
So I take the liberty to close this issue.

**Closed by Canialon** 2022-05-25 15:38 UTC
Labels: bug
