### ISSUE TITLE
[FEATURE REQUEST]: Tutorial for each pages

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#942] opened 2021-05-25 08:28 UTC
**Is your feature request related to a problem? Please describe.**

No tutorials are present in the app right now

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

#941

**Comment by smk762** [comment] 2022-02-06 09:07
While the UI of the app is still being improved, I think this might be better served as video / docs, with links available to users in the FAQ section, and updated whenever a release includes significant changes or new features.

**Comment by smk762** [comment] 2022-07-05 07:03
Duplicate of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/450

**Closed by smk762** 2022-07-05 07:03 UTC
