### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mantrid123** [KomodoPlatform/atomicDEX-Desktop#2222] opened 2023-03-05 22:55 UTC
Add MEMO for BEP 2,0 ANKR deposits please.

**Comment by cipig** [comment] 2023-03-06 05:09
BEP2 tokens are not supported, only BEP20... and those don't have any MEMO
we need MEMO, just not for BEP2, but for ARRR: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2205

**Comment by smk762** [comment] 2023-04-01 09:16
Closing, duplicate of https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2205

**Closed by smk762** 2023-04-01 09:16 UTC
Labels: bug
